"""use English column comments

Revision ID: 0005_english_column_comments
Revises: 0004_user_exam_targets
Create Date: 2026-09-21 14:02:33.368107
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


revision: str = '0005_english_column_comments'
down_revision: Union[str, None] = '0004_user_exam_targets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer_records', 'id',
               existing_type=mysql.INTEGER(),
               comment='Record ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('answer_records', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='User ID',
               existing_nullable=False)
    op.alter_column('answer_records', 'paper_id',
               existing_type=mysql.INTEGER(),
               comment='Paper ID',
               existing_nullable=False)
    op.alter_column('answer_records', 'question_id',
               existing_type=mysql.INTEGER(),
               comment='Question ID',
               existing_nullable=False)
    op.alter_column('answer_records', 'user_answer',
               existing_type=mysql.VARCHAR(length=256),
               comment='Submitted answer',
               existing_nullable=True)
    op.alter_column('answer_records', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Whether the submitted answer is correct',
               existing_nullable=True)
    op.alter_column('answer_records', 'time_spent',
               existing_type=mysql.INTEGER(),
               comment='Time spent on this question in seconds',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('answer_records', 'wrong_reason',
               existing_type=mysql.ENUM('知识点不会', '粗心大意', '审题错误', '时间不够', '选项混淆', '其他'),
               comment='Incorrect-answer reason tag',
               existing_nullable=True)
    op.alter_column('answer_records', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='Submission time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'answer_records',
        'Answer submission records',
        existing_comment='答题记录表',
        schema=None
    )
    op.alter_column('content_items', 'id',
               existing_type=mysql.INTEGER(),
               comment='Content ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('content_items', 'category',
               existing_type=mysql.ENUM('consulting', 'club', 'ad', 'notice'),
               comment='Content category',
               existing_nullable=False)
    op.alter_column('content_items', 'title',
               existing_type=mysql.VARCHAR(length=128),
               comment='Title',
               existing_nullable=False)
    op.alter_column('content_items', 'summary',
               existing_type=mysql.VARCHAR(length=255),
               comment='Summary',
               existing_nullable=False)
    op.alter_column('content_items', 'body',
               existing_type=mysql.TEXT(),
               comment='Body content',
               existing_nullable=False)
    op.alter_column('content_items', 'cover_image',
               existing_type=mysql.VARCHAR(length=512),
               comment='Cover image URL',
               existing_nullable=True)
    op.alter_column('content_items', 'link_url',
               existing_type=mysql.VARCHAR(length=512),
               comment='Destination URL',
               existing_nullable=True)
    op.alter_column('content_items', 'sort_order',
               existing_type=mysql.INTEGER(),
               comment='Display order',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('content_items', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Whether the content is active',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('content_items', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('content_items', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='Update time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'content_items',
        'Home news and promotional content',
        existing_comment='首页资讯和广告内容表',
        schema=None
    )
    op.alter_column('favorites', 'id',
               existing_type=mysql.INTEGER(),
               comment='Favorite ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('favorites', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='User ID',
               existing_nullable=False)
    op.alter_column('favorites', 'question_id',
               existing_type=mysql.INTEGER(),
               comment='Question ID',
               existing_nullable=False)
    op.alter_column('favorites', 'note',
               existing_type=mysql.VARCHAR(length=256),
               comment='Favorite note',
               existing_nullable=True)
    op.alter_column('favorites', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'favorites',
        'User favorite questions',
        existing_comment='收藏题目表',
        schema=None
    )
    op.alter_column('knowledge_stats', 'id',
               existing_type=mysql.INTEGER(),
               comment='Statistics ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('knowledge_stats', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='User ID',
               existing_nullable=False)
    op.alter_column('knowledge_stats', 'exam_type',
               existing_type=mysql.ENUM('CSCA', 'HKS'),
               comment='Exam type',
               existing_nullable=False)
    op.alter_column('knowledge_stats', 'knowledge_point',
               existing_type=mysql.VARCHAR(length=64),
               comment='Knowledge point',
               existing_nullable=False)
    op.alter_column('knowledge_stats', 'total_answered',
               existing_type=mysql.INTEGER(),
               comment='Total answers',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('knowledge_stats', 'total_correct',
               existing_type=mysql.INTEGER(),
               comment='Total correct answers',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('knowledge_stats', 'correct_rate',
               existing_type=mysql.FLOAT(),
               comment='Correct answer rate',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_table_comment(
        'knowledge_stats',
        'Knowledge-point performance statistics',
        existing_comment='知识点统计表',
        schema=None
    )
    op.alter_column('papers', 'id',
               existing_type=mysql.INTEGER(),
               comment='Paper ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('papers', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='Creator user ID',
               existing_nullable=False)
    op.alter_column('papers', 'title',
               existing_type=mysql.VARCHAR(length=128),
               comment='Paper title',
               existing_nullable=False)
    op.alter_column('papers', 'exam_type',
               existing_type=mysql.ENUM('CSCA', 'HKS'),
               comment='Exam type',
               existing_nullable=False)
    op.alter_column('papers', 'strategy',
               existing_type=mysql.ENUM('random', 'knowledge', 'progressive', 'real'),
               comment='Paper generation strategy',
               existing_nullable=False)
    op.alter_column('papers', 'question_ids',
               existing_type=mysql.JSON(),
               comment='Ordered list of question IDs',
               existing_nullable=False)
    op.alter_column('papers', 'total_score',
               existing_type=mysql.INTEGER(),
               comment='Total score',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('papers', 'time_limit',
               existing_type=mysql.INTEGER(),
               comment='Time limit in minutes; zero means unlimited',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('papers', 'mode',
               existing_type=mysql.ENUM('exam', 'practice'),
               comment='Answer mode',
               existing_nullable=True,
               existing_server_default=sa.text("'practice'"))
    op.alter_column('papers', 'difficulty',
               existing_type=mysql.ENUM('all', 'easy', 'medium', 'hard'),
               comment='Difficulty filter',
               existing_nullable=True,
               existing_server_default=sa.text("'all'"))
    op.alter_column('papers', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Whether the paper is publicly shared',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('papers', 'finished_at',
               existing_type=mysql.DATETIME(),
               comment='Completion time',
               existing_nullable=True)
    op.create_table_comment(
        'papers',
        'Generated exam papers',
        existing_comment='试卷表',
        schema=None
    )
    op.alter_column('questions', 'id',
               existing_type=mysql.INTEGER(),
               comment='Question ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('questions', 'exam_type',
               existing_type=mysql.ENUM('CSCA', 'HKS'),
               comment='Exam type',
               existing_nullable=False)
    op.alter_column('questions', 'subject',
               existing_type=mysql.VARCHAR(length=32),
               comment='Subject',
               existing_nullable=False)
    op.alter_column('questions', 'knowledge_point',
               existing_type=mysql.VARCHAR(length=64),
               comment='Knowledge point tag',
               existing_nullable=False)
    op.alter_column('questions', 'difficulty',
               existing_type=mysql.ENUM('easy', 'medium', 'hard'),
               comment='Difficulty',
               existing_nullable=False)
    op.alter_column('questions', 'question_type',
               existing_type=mysql.ENUM('single', 'multi', 'judge', 'fill'),
               comment='Question type',
               existing_nullable=False)
    op.alter_column('questions', 'stem_text',
               existing_type=mysql.TEXT(),
               comment='Question stem text',
               existing_nullable=False)
    op.alter_column('questions', 'stem_image',
               existing_type=mysql.VARCHAR(length=512),
               comment='Question stem image URL',
               existing_nullable=True)
    op.alter_column('questions', 'stem_audio',
               existing_type=mysql.VARCHAR(length=512),
               comment='Question stem audio URL',
               existing_nullable=True)
    op.alter_column('questions', 'options',
               existing_type=mysql.JSON(),
               comment='Options in [{key, text}] format',
               existing_nullable=False)
    op.alter_column('questions', 'answer',
               existing_type=mysql.VARCHAR(length=256),
               comment='Correct answer',
               existing_nullable=False)
    op.alter_column('questions', 'analysis',
               existing_type=mysql.TEXT(),
               comment='Answer explanation',
               existing_nullable=True)
    op.alter_column('questions', 'wrong_options_analysis',
               existing_type=mysql.JSON(),
               comment='Distractor analysis',
               existing_nullable=True)
    op.alter_column('questions', 'usage_count',
               existing_type=mysql.INTEGER(),
               comment='Times included in papers',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('questions', 'correct_count',
               existing_type=mysql.INTEGER(),
               comment='Correct answer count',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('questions', 'wrong_count',
               existing_type=mysql.INTEGER(),
               comment='Incorrect answer count',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('questions', 'wrong_rate',
               existing_type=mysql.FLOAT(),
               comment='Historical incorrect rate',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('questions', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Whether the question is active',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.create_table_comment(
        'questions',
        'Question bank',
        existing_comment='题目表',
        schema=None
    )
    op.alter_column('streak_records', 'id',
               existing_type=mysql.INTEGER(),
               comment='Record ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('streak_records', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='User ID',
               existing_nullable=False)
    op.alter_column('streak_records', 'streak_date',
               existing_type=sa.DATE(),
               comment='Study date',
               existing_nullable=False)
    op.alter_column('streak_records', 'question_count',
               existing_type=mysql.INTEGER(),
               comment='Questions answered that day',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_table_comment(
        'streak_records',
        'Daily study streak records',
        existing_comment='打卡记录表',
        schema=None
    )
    op.alter_column('user_exam_targets', 'id',
               existing_type=mysql.INTEGER(),
               comment='Record ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_exam_targets', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='User ID',
               existing_nullable=False)
    op.alter_column('user_exam_targets', 'exam_type',
               existing_type=mysql.ENUM('CSCA', 'HKS'),
               comment='Exam type',
               existing_nullable=False)
    op.alter_column('user_exam_targets', 'target_date',
               existing_type=sa.DATE(),
               comment='Target date for this exam',
               existing_nullable=False)
    op.alter_column('user_exam_targets', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'user_exam_targets',
        'Per-exam target dates for users',
        existing_comment='用户各考试目标日期',
        schema=None
    )
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               comment='User ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'openid',
               existing_type=mysql.VARCHAR(length=64),
               comment='WeChat OpenID',
               existing_nullable=False)
    op.alter_column('users', 'unionid',
               existing_type=mysql.VARCHAR(length=64),
               comment='WeChat UnionID for cross-app identity',
               existing_nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=mysql.VARCHAR(length=64),
               comment='Display name',
               existing_nullable=True,
               existing_server_default=sa.text("'考霸同学'"))
    op.alter_column('users', 'avatar_url',
               existing_type=mysql.VARCHAR(length=512),
               comment='Avatar URL',
               existing_nullable=True)
    op.alter_column('users', 'target_exam',
               existing_type=mysql.ENUM('CSCA', 'HKS'),
               comment='Primary target exam',
               existing_nullable=True,
               existing_server_default=sa.text("'CSCA'"))
    op.alter_column('users', 'target_date',
               existing_type=sa.DATE(),
               comment='Primary target exam date',
               existing_nullable=True)
    op.alter_column('users', 'total_questions',
               existing_type=mysql.INTEGER(),
               comment='Total questions answered',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'total_correct',
               existing_type=mysql.INTEGER(),
               comment='Total correct answers',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'streak_days',
               existing_type=mysql.INTEGER(),
               comment='Current study streak in days',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'last_streak_at',
               existing_type=sa.DATE(),
               comment='Most recent streak date',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='Registration time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'users',
        'Application users',
        existing_comment='用户表',
        schema=None
    )
    op.alter_column('wrong_book', 'id',
               existing_type=mysql.INTEGER(),
               comment='Record ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('wrong_book', 'user_id',
               existing_type=mysql.INTEGER(),
               comment='User ID',
               existing_nullable=False)
    op.alter_column('wrong_book', 'question_id',
               existing_type=mysql.INTEGER(),
               comment='Question ID',
               existing_nullable=False)
    op.alter_column('wrong_book', 'wrong_count',
               existing_type=mysql.INTEGER(),
               comment='Cumulative incorrect-answer count',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('wrong_book', 'correct_count',
               existing_type=mysql.INTEGER(),
               comment='Consecutive correct-answer count',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('wrong_book', 'is_mastered',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Whether mastered after the required correct-answer streak',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('wrong_book', 'first_wrong_at',
               existing_type=mysql.DATETIME(),
               comment='First incorrect-answer time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('wrong_book', 'last_wrong_at',
               existing_type=mysql.DATETIME(),
               comment='Most recent incorrect-answer time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('wrong_book', 'last_review_at',
               existing_type=mysql.DATETIME(),
               comment='Most recent review time',
               existing_nullable=True)
    op.create_table_comment(
        'wrong_book',
        'User wrong-book entries',
        existing_comment='错题本表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'wrong_book',
        '错题本表',
        existing_comment='User wrong-book entries',
        schema=None
    )
    op.alter_column('wrong_book', 'last_review_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Most recent review time',
               existing_nullable=True)
    op.alter_column('wrong_book', 'last_wrong_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Most recent incorrect-answer time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('wrong_book', 'first_wrong_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='First incorrect-answer time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('wrong_book', 'is_mastered',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Whether mastered after the required correct-answer streak',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('wrong_book', 'correct_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Consecutive correct-answer count',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('wrong_book', 'wrong_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Cumulative incorrect-answer count',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('wrong_book', 'question_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Question ID',
               existing_nullable=False)
    op.alter_column('wrong_book', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='User ID',
               existing_nullable=False)
    op.alter_column('wrong_book', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Record ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'users',
        '用户表',
        existing_comment='Application users',
        schema=None
    )
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Registration time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'last_streak_at',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Most recent streak date',
               existing_nullable=True)
    op.alter_column('users', 'streak_days',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Current study streak in days',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'total_correct',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Total correct answers',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'total_questions',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Total questions answered',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'target_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Primary target exam date',
               existing_nullable=True)
    op.alter_column('users', 'target_exam',
               existing_type=mysql.ENUM('CSCA', 'HKS'),
               comment=None,
               existing_comment='Primary target exam',
               existing_nullable=True,
               existing_server_default=sa.text("'CSCA'"))
    op.alter_column('users', 'avatar_url',
               existing_type=mysql.VARCHAR(length=512),
               comment=None,
               existing_comment='Avatar URL',
               existing_nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='Display name',
               existing_nullable=True,
               existing_server_default=sa.text("'考霸同学'"))
    op.alter_column('users', 'unionid',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='WeChat UnionID for cross-app identity',
               existing_nullable=True)
    op.alter_column('users', 'openid',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='WeChat OpenID',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='User ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'user_exam_targets',
        '用户各考试目标日期',
        existing_comment='Per-exam target dates for users',
        schema=None
    )
    op.alter_column('user_exam_targets', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_exam_targets', 'target_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Target date for this exam',
               existing_nullable=False)
    op.alter_column('user_exam_targets', 'exam_type',
               existing_type=mysql.ENUM('CSCA', 'HKS'),
               comment=None,
               existing_comment='Exam type',
               existing_nullable=False)
    op.alter_column('user_exam_targets', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='User ID',
               existing_nullable=False)
    op.alter_column('user_exam_targets', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Record ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'streak_records',
        '打卡记录表',
        existing_comment='Daily study streak records',
        schema=None
    )
    op.alter_column('streak_records', 'question_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Questions answered that day',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('streak_records', 'streak_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Study date',
               existing_nullable=False)
    op.alter_column('streak_records', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='User ID',
               existing_nullable=False)
    op.alter_column('streak_records', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Record ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'questions',
        '题目表',
        existing_comment='Question bank',
        schema=None
    )
    op.alter_column('questions', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Whether the question is active',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('questions', 'wrong_rate',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='Historical incorrect rate',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('questions', 'wrong_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Incorrect answer count',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('questions', 'correct_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Correct answer count',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('questions', 'usage_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Times included in papers',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('questions', 'wrong_options_analysis',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Distractor analysis',
               existing_nullable=True)
    op.alter_column('questions', 'analysis',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Answer explanation',
               existing_nullable=True)
    op.alter_column('questions', 'answer',
               existing_type=mysql.VARCHAR(length=256),
               comment=None,
               existing_comment='Correct answer',
               existing_nullable=False)
    op.alter_column('questions', 'options',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Options in [{key, text}] format',
               existing_nullable=False)
    op.alter_column('questions', 'stem_audio',
               existing_type=mysql.VARCHAR(length=512),
               comment=None,
               existing_comment='Question stem audio URL',
               existing_nullable=True)
    op.alter_column('questions', 'stem_image',
               existing_type=mysql.VARCHAR(length=512),
               comment=None,
               existing_comment='Question stem image URL',
               existing_nullable=True)
    op.alter_column('questions', 'stem_text',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Question stem text',
               existing_nullable=False)
    op.alter_column('questions', 'question_type',
               existing_type=mysql.ENUM('single', 'multi', 'judge', 'fill'),
               comment=None,
               existing_comment='Question type',
               existing_nullable=False)
    op.alter_column('questions', 'difficulty',
               existing_type=mysql.ENUM('easy', 'medium', 'hard'),
               comment=None,
               existing_comment='Difficulty',
               existing_nullable=False)
    op.alter_column('questions', 'knowledge_point',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='Knowledge point tag',
               existing_nullable=False)
    op.alter_column('questions', 'subject',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='Subject',
               existing_nullable=False)
    op.alter_column('questions', 'exam_type',
               existing_type=mysql.ENUM('CSCA', 'HKS'),
               comment=None,
               existing_comment='Exam type',
               existing_nullable=False)
    op.alter_column('questions', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Question ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'papers',
        '试卷表',
        existing_comment='Generated exam papers',
        schema=None
    )
    op.alter_column('papers', 'finished_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Completion time',
               existing_nullable=True)
    op.alter_column('papers', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Whether the paper is publicly shared',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('papers', 'difficulty',
               existing_type=mysql.ENUM('all', 'easy', 'medium', 'hard'),
               comment=None,
               existing_comment='Difficulty filter',
               existing_nullable=True,
               existing_server_default=sa.text("'all'"))
    op.alter_column('papers', 'mode',
               existing_type=mysql.ENUM('exam', 'practice'),
               comment=None,
               existing_comment='Answer mode',
               existing_nullable=True,
               existing_server_default=sa.text("'practice'"))
    op.alter_column('papers', 'time_limit',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Time limit in minutes; zero means unlimited',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('papers', 'total_score',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Total score',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('papers', 'question_ids',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Ordered list of question IDs',
               existing_nullable=False)
    op.alter_column('papers', 'strategy',
               existing_type=mysql.ENUM('random', 'knowledge', 'progressive', 'real'),
               comment=None,
               existing_comment='Paper generation strategy',
               existing_nullable=False)
    op.alter_column('papers', 'exam_type',
               existing_type=mysql.ENUM('CSCA', 'HKS'),
               comment=None,
               existing_comment='Exam type',
               existing_nullable=False)
    op.alter_column('papers', 'title',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='Paper title',
               existing_nullable=False)
    op.alter_column('papers', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Creator user ID',
               existing_nullable=False)
    op.alter_column('papers', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Paper ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'knowledge_stats',
        '知识点统计表',
        existing_comment='Knowledge-point performance statistics',
        schema=None
    )
    op.alter_column('knowledge_stats', 'correct_rate',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='Correct answer rate',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('knowledge_stats', 'total_correct',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Total correct answers',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('knowledge_stats', 'total_answered',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Total answers',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('knowledge_stats', 'knowledge_point',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='Knowledge point',
               existing_nullable=False)
    op.alter_column('knowledge_stats', 'exam_type',
               existing_type=mysql.ENUM('CSCA', 'HKS'),
               comment=None,
               existing_comment='Exam type',
               existing_nullable=False)
    op.alter_column('knowledge_stats', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='User ID',
               existing_nullable=False)
    op.alter_column('knowledge_stats', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Statistics ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'favorites',
        '收藏题目表',
        existing_comment='User favorite questions',
        schema=None
    )
    op.alter_column('favorites', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('favorites', 'note',
               existing_type=mysql.VARCHAR(length=256),
               comment=None,
               existing_comment='Favorite note',
               existing_nullable=True)
    op.alter_column('favorites', 'question_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Question ID',
               existing_nullable=False)
    op.alter_column('favorites', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='User ID',
               existing_nullable=False)
    op.alter_column('favorites', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Favorite ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'content_items',
        '首页资讯和广告内容表',
        existing_comment='Home news and promotional content',
        schema=None
    )
    op.alter_column('content_items', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Update time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('content_items', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Creation time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('content_items', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Whether the content is active',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('content_items', 'sort_order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Display order',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('content_items', 'link_url',
               existing_type=mysql.VARCHAR(length=512),
               comment=None,
               existing_comment='Destination URL',
               existing_nullable=True)
    op.alter_column('content_items', 'cover_image',
               existing_type=mysql.VARCHAR(length=512),
               comment=None,
               existing_comment='Cover image URL',
               existing_nullable=True)
    op.alter_column('content_items', 'body',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Body content',
               existing_nullable=False)
    op.alter_column('content_items', 'summary',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='Summary',
               existing_nullable=False)
    op.alter_column('content_items', 'title',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='Title',
               existing_nullable=False)
    op.alter_column('content_items', 'category',
               existing_type=mysql.ENUM('consulting', 'club', 'ad', 'notice'),
               comment=None,
               existing_comment='Content category',
               existing_nullable=False)
    op.alter_column('content_items', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Content ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'answer_records',
        '答题记录表',
        existing_comment='Answer submission records',
        schema=None
    )
    op.alter_column('answer_records', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Submission time',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('answer_records', 'wrong_reason',
               existing_type=mysql.ENUM('知识点不会', '粗心大意', '审题错误', '时间不够', '选项混淆', '其他'),
               comment=None,
               existing_comment='Incorrect-answer reason tag',
               existing_nullable=True)
    op.alter_column('answer_records', 'time_spent',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Time spent on this question in seconds',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('answer_records', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Whether the submitted answer is correct',
               existing_nullable=True)
    op.alter_column('answer_records', 'user_answer',
               existing_type=mysql.VARCHAR(length=256),
               comment=None,
               existing_comment='Submitted answer',
               existing_nullable=True)
    op.alter_column('answer_records', 'question_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Question ID',
               existing_nullable=False)
    op.alter_column('answer_records', 'paper_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Paper ID',
               existing_nullable=False)
    op.alter_column('answer_records', 'user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='User ID',
               existing_nullable=False)
    op.alter_column('answer_records', 'id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Record ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
